/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MoradorController;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import model.Morador;

/**
 *
 * @author Isabela Nunes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/repme.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jtfLogin = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        jBtnAcesso = new org.edisoncor.gui.button.ButtonSeven();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonRound1 = new org.edisoncor.gui.button.ButtonRound();
        jLabel3 = new javax.swing.JLabel();
        passwordFieldRoundBackground1 = new org.edisoncor.gui.passwordField.PasswordFieldRoundBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 530));
        getContentPane().setLayout(null);

        panelImage2.setBackground(new java.awt.Color(255, 0, 0));
        panelImage2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg.png"))); // NOI18N
        panelImage2.setMinimumSize(new java.awt.Dimension(630, 450));
        panelImage2.setPreferredSize(new java.awt.Dimension(630, 450));
        panelImage2.setLayout(null);

        jtfLogin.setForeground(new java.awt.Color(153, 153, 153));
        jtfLogin.setToolTipText("");
        jtfLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panelImage2.add(jtfLogin);
        jtfLogin.setBounds(320, 230, 168, 30);

        jBtnAcesso.setBackground(java.awt.SystemColor.textHighlight);
        jBtnAcesso.setText("acessar");
        jBtnAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAcessoActionPerformed(evt);
            }
        });
        panelImage2.add(jBtnAcesso);
        jBtnAcesso.setBounds(290, 360, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/password2.png"))); // NOI18N
        panelImage2.add(jLabel1);
        jLabel1.setBounds(280, 270, 30, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/user2.png"))); // NOI18N
        panelImage2.add(jLabel2);
        jLabel2.setBounds(280, 230, 30, 30);

        buttonRound1.setBackground(new java.awt.Color(255, 255, 255));
        buttonRound1.setForeground(new java.awt.Color(0, 0, 0));
        buttonRound1.setText("Cadastrar-se");
        buttonRound1.setColorDeSombra(new java.awt.Color(255, 255, 255));
        buttonRound1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        panelImage2.add(buttonRound1);
        buttonRound1.setBounds(220, 420, 300, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Anotação 2019-09-28 092152.png"))); // NOI18N
        panelImage2.add(jLabel3);
        jLabel3.setBounds(260, 60, 230, 140);

        passwordFieldRoundBackground1.setText("passwordFieldRoundBackground1");
        passwordFieldRoundBackground1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldRoundBackground1ActionPerformed(evt);
            }
        });
        panelImage2.add(passwordFieldRoundBackground1);
        passwordFieldRoundBackground1.setBounds(320, 280, 170, 30);

        getContentPane().add(panelImage2);
        panelImage2.setBounds(0, 0, 750, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        CadastroUsuario cadastroMorador = new CadastroUsuario(null);
        cadastroMorador.setVisible(true);
        CadastroUsuario.btnCadastrarConta.setVisible(false);
        CadastroUsuario.btnConsultarConta.setVisible(false);
        CadastroUsuario.btnConsultarSaldo.setVisible(false);
        CadastroUsuario.labelSaldo.setVisible(false);
        CadastroUsuario.jtfSaldo.setVisible(false);
        CadastroUsuario.jlblLogin.setVisible(true);
        CadastroUsuario.jlblSenha.setVisible(true);
        CadastroUsuario.jtfLogin.setVisible(true);
        CadastroUsuario.jtfSenha.setVisible(true);
        CadastroUsuario.btnCadastrar.setVisible(true);
        CadastroUsuario.btnAlterar.setVisible(false);
        CadastroUsuario.btnCadastrar.setBackground(new Color(102, 255, 102));
        CadastroUsuario.btnCadastrar.setText("CADASTRAR");
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void jBtnAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAcessoActionPerformed
        // TODO add your handling code here:

        Morador morador = new Morador();

        morador.setLogin(jtfLogin.getText());
        morador.setSenha(jtfSenha.getText());
        Morador usuario = new Morador();

        try {
            MoradorController moradorController = new MoradorController();

            usuario = moradorController.login(morador);
            Menu menu = new Menu(usuario);
            menu.setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            System.out.println("Problemas ao cadastrar Pessoa na View!  Erro: " + ex.getMessage());
            ex.printStackTrace();
        }

        if (usuario != null) {
            System.out.println(usuario.getNome());
        } else {

            System.out.print("Login ou senha não são válidos");

        };


    }//GEN-LAST:event_jBtnAcessoActionPerformed

    private void passwordFieldRoundBackground1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldRoundBackground1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldRoundBackground1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound buttonRound1;
    private org.edisoncor.gui.button.ButtonSeven jBtnAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.edisoncor.gui.textField.TextFieldRoundIcon jtfLogin;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundBackground passwordFieldRoundBackground1;
    // End of variables declaration//GEN-END:variables
}
