/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Morador;
import view.Menu;
import view.Menu;

/**
 *
 * @author Isabela Nunes
 */
public class CadastroMorador extends javax.swing.JFrame {

    Morador mor = new Morador();
    Morador usuario = new Morador();

    /**
     * Creates new form CadastroMorador
     */
    public CadastroMorador() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/repme.png")).getImage());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelNice5 = new org.edisoncor.gui.panel.PanelNice();
        panelNice6 = new org.edisoncor.gui.panel.PanelNice();
        labelRound1 = new org.edisoncor.gui.label.LabelRound();
        jlblUser2 = new javax.swing.JLabel();
        btnCadastrar = new org.edisoncor.gui.button.ButtonAeroRound();
        jtfEmail = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jlblUser5 = new javax.swing.JLabel();
        jtfSaldo = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelSaldo = new org.edisoncor.gui.label.LabelHeader();
        jtfSobrenome = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jlblLogin = new javax.swing.JLabel();
        jtfLogin = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jlblSenha = new javax.swing.JLabel();
        jtfSenha = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        jtfNome = new org.edisoncor.gui.textField.TextFieldRectBackground();
        btnAlterar = new org.edisoncor.gui.button.ButtonAeroRound();
        labelSaldo1 = new org.edisoncor.gui.label.LabelHeader();
        jtfSobrenome1 = new org.edisoncor.gui.textField.TextFieldRectBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg2.png"))); // NOI18N

        panelNice5.setBackground(new java.awt.Color(255, 255, 255));
        panelNice5.setLayout(null);

        panelNice6.setBackground(new java.awt.Color(255, 255, 255));
        panelNice6.setLayout(null);
        panelNice5.add(panelNice6);
        panelNice6.setBounds(0, 0, 0, 0);

        labelRound1.setForeground(new java.awt.Color(0, 0, 0));
        labelRound1.setText("MORADOR");
        labelRound1.setColorDeSegundoBorde(new java.awt.Color(204, 204, 204));
        labelRound1.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelRound1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelRound1.setName(""); // NOI18N
        panelNice5.add(labelRound1);
        labelRound1.setBounds(0, 0, 540, 40);

        jlblUser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblUser2.setText("NOME");
        panelNice5.add(jlblUser2);
        jlblUser2.setBounds(60, 40, 80, 30);

        btnCadastrar.setBackground(new java.awt.Color(204, 0, 0));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setFocusTraversalPolicyProvider(true);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        panelNice5.add(btnCadastrar);
        btnCadastrar.setBounds(180, 350, 170, 40);

        jtfEmail.setDescripcion("ex: usuario@gmail.com");
        panelNice5.add(jtfEmail);
        jtfEmail.setBounds(60, 140, 420, 40);

        jlblUser5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblUser5.setText("E-MAIL");
        panelNice5.add(jlblUser5);
        jlblUser5.setBounds(60, 110, 120, 30);

        jtfSaldo.setDescripcion("R$ 00,00");
        jtfSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSaldoActionPerformed(evt);
            }
        });
        panelNice5.add(jtfSaldo);
        jtfSaldo.setBounds(60, 300, 160, 40);

        labelSaldo.setText("REPÚBLICA");
        panelNice5.add(labelSaldo);
        labelSaldo.setBounds(310, 260, 140, 40);

        jtfSobrenome.setDescripcion("República");
        jtfSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSobrenomeActionPerformed(evt);
            }
        });
        panelNice5.add(jtfSobrenome);
        jtfSobrenome.setBounds(270, 300, 230, 40);

        jlblLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblLogin.setText("LOGIN");
        panelNice5.add(jlblLogin);
        jlblLogin.setBounds(60, 180, 80, 30);

        jtfLogin.setDescripcion("Insira o login");
        panelNice5.add(jtfLogin);
        jtfLogin.setBounds(60, 210, 180, 40);

        jlblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblSenha.setText("SENHA");
        panelNice5.add(jlblSenha);
        jlblSenha.setBounds(300, 180, 80, 30);

        jtfSenha.setDescripcion("Informe a senha");
        panelNice5.add(jtfSenha);
        jtfSenha.setBounds(300, 210, 170, 40);

        jtfNome.setDescripcion("Primeiro nome");
        panelNice5.add(jtfNome);
        jtfNome.setBounds(60, 70, 160, 40);

        btnAlterar.setBackground(new java.awt.Color(204, 0, 0));
        btnAlterar.setText("ALTERAR");
        btnAlterar.setFocusTraversalPolicyProvider(true);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        panelNice5.add(btnAlterar);
        btnAlterar.setBounds(180, 350, 170, 40);

        labelSaldo1.setText("SALDO");
        panelNice5.add(labelSaldo1);
        labelSaldo1.setBounds(70, 260, 140, 40);

        jtfSobrenome1.setDescripcion("Sobrenome");
        panelNice5.add(jtfSobrenome1);
        jtfSobrenome1.setBounds(240, 70, 230, 40);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(panelNice5, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(panelNice5, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jtfSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSaldoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jtfSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSobrenomeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CadastroMorador().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.edisoncor.gui.button.ButtonAeroRound btnAlterar;
    public static org.edisoncor.gui.button.ButtonAeroRound btnCadastrar;
    public static javax.swing.JLabel jlblLogin;
    public static javax.swing.JLabel jlblSenha;
    private javax.swing.JLabel jlblUser2;
    private javax.swing.JLabel jlblUser5;
    public static org.edisoncor.gui.textField.TextFieldRectBackground jtfEmail;
    public static org.edisoncor.gui.textField.TextFieldRectBackground jtfLogin;
    public static org.edisoncor.gui.textField.TextFieldRectBackground jtfNome;
    public static org.edisoncor.gui.textField.TextFieldRectBackground jtfSaldo;
    public static org.edisoncor.gui.passwordField.PasswordFieldRectBackground jtfSenha;
    public static org.edisoncor.gui.textField.TextFieldRectBackground jtfSobrenome;
    public static org.edisoncor.gui.textField.TextFieldRectBackground jtfSobrenome1;
    private org.edisoncor.gui.label.LabelRound labelRound1;
    public static org.edisoncor.gui.label.LabelHeader labelSaldo;
    public static org.edisoncor.gui.label.LabelHeader labelSaldo1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static org.edisoncor.gui.panel.PanelNice panelNice5;
    private org.edisoncor.gui.panel.PanelNice panelNice6;
    // End of variables declaration//GEN-END:variables
}
