/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import controller.CompartilhadoController;
import controller.MoradorController;
//import controller.PessoalController;
import java.awt.Color;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ImageIcon;
//import model.Compartilhado;
//import model.Conta;
import model.Morador;

/**
 *
 * @author Isabela Nunes
 */
public class Menu extends javax.swing.JFrame {

    Morador usuario = new Morador();

    /**
     * Creates new form Menu
     */
    public Menu(Morador mor) {
        initComponents();
        jLblNome.setText(mor.getNome() + "!");
        jlblSaldo.setText("R$ " + Double.toString(mor.getSaldo()));
        saudacao();
        usuario = mor;
        setSaldo();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/repme.png")).getImage());
        
    }

    Menu() {
    }

    public String getHora() {
        // cria um StringBuilder
        StringBuilder sb = new StringBuilder();
        // cria um GregorianCalendar que vai conter a hora atual
        GregorianCalendar d = new GregorianCalendar();
        // anexa do StringBuilder os dados da hora
        sb.append(d.get(GregorianCalendar.HOUR_OF_DAY));
        //sb.append( ":" );
        //sb.append( d.get( GregorianCalendar.MINUTE ) );
        //sb.append( ":" );
        //sb.append( d.get( GregorianCalendar.SECOND ) );
        // retorna a String do StringBuilder
        return sb.toString();
    }

    public void saudacao() {
        lblHora.setText(getHora());
        int hora = Integer.parseInt(lblHora.getText());
        //System.out.println("hora");
        if (hora >= 12 && hora < 18) {
            jLblSaudacao.setText("Boa tarde,");
        } else if (hora > 0 && hora < 12) {
            jLblSaudacao.setText("Bom dia,");
        } else {
            jLblSaudacao.setText("Boa noite,");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelNice5 = new org.edisoncor.gui.panel.PanelNice();
        panelNice6 = new org.edisoncor.gui.panel.PanelNice();
        labelRound1 = new org.edisoncor.gui.label.LabelRound();
        lblHora = new javax.swing.JLabel();
        jLblSaudacao = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrarConta = new javax.swing.JLabel();
        btnConsultarSaldo = new javax.swing.JLabel();
        btnConsultarConta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg2.png"))); // NOI18N

        panelNice5.setBackground(new java.awt.Color(255, 255, 255));
        panelNice5.setLayout(null);

        panelNice6.setBackground(new java.awt.Color(255, 255, 255));
        panelNice6.setLayout(null);
        panelNice5.add(panelNice6);
        panelNice6.setBounds(0, 0, 0, 0);

        labelRound1.setForeground(new java.awt.Color(0, 0, 0));
        labelRound1.setText("MENU");
        labelRound1.setColorDeSegundoBorde(new java.awt.Color(204, 204, 204));
        labelRound1.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelRound1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelRound1.setName(""); // NOI18N
        panelNice5.add(labelRound1);
        labelRound1.setBounds(0, 0, 530, 40);

        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        panelNice5.add(lblHora);
        lblHora.setBounds(450, 210, 34, 14);

        jLblSaudacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblSaudacao.setText("Bom dia,");
        panelNice5.add(jLblSaudacao);
        jLblSaudacao.setBounds(80, 60, 100, 30);

        jLblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelNice5.add(jLblNome);
        jLblNome.setBounds(80, 100, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelNice5.add(jLabel2);
        jLabel2.setBounds(40, 80, 30, 40);

        jlblSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblSaldo.setText("R$ 00,00");
        panelNice5.add(jlblSaldo);
        jlblSaldo.setBounds(80, 170, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coins.png"))); // NOI18N
        panelNice5.add(jLabel3);
        jLabel3.setBounds(40, 150, 40, 40);

        btnCadastrarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator.png"))); // NOI18N
        btnCadastrarConta.setText("Cadastrar Conta");
        btnCadastrarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarContaMouseClicked(evt);
            }
        });
        panelNice5.add(btnCadastrarConta);
        btnCadastrarConta.setBounds(40, 220, 150, 50);

        btnConsultarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money.png"))); // NOI18N
        btnConsultarSaldo.setText("Consultar Saldos");
        btnConsultarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarSaldoMouseClicked(evt);
            }
        });
        panelNice5.add(btnConsultarSaldo);
        btnConsultarSaldo.setBounds(210, 230, 140, 40);

        btnConsultarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/searchCount.png"))); // NOI18N
        btnConsultarConta.setText(" Consultar Contas");
        btnConsultarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarContaMouseClicked(evt);
            }
        });
        panelNice5.add(btnConsultarConta);
        btnConsultarConta.setBounds(390, 230, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SALDO");
        panelNice5.add(jLabel1);
        jLabel1.setBounds(80, 140, 70, 30);
        panelNice5.add(clockFace1);
        clockFace1.setBounds(370, 40, 150, 150);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(panelNice5, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelNice5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarContaMouseClicked

        Morador mor = new Morador();
        try {

            mor = MoradorController.login(usuario);
           // CadastrarConta cadastrarConta = new CadastrarConta(mor);
            //cadastrarConta.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            System.out.println("Problemas ao cadastrar Pessoa na View!  Erro: " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnCadastrarContaMouseClicked

    private void btnConsultarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoMouseClicked
        // TODO add your handling code here:
        Morador mor = new Morador();
        try {
            MoradorController moradorController = new MoradorController();

            //mor = moradorController.login(usuario);
            //ConsultarSaldos consultarSaldos = new ConsultarSaldos(mor);
           // consultarSaldos.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            System.out.println("Problemas ao cadastrar Pessoa na View!  Erro: " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnConsultarSaldoMouseClicked

    private void btnConsultarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarContaMouseClicked
        // TODO add your handling code here:
        Morador mor = new Morador();
        try {
            MoradorController moradorController = new MoradorController();

           // mor = moradorController.login(usuario);
           // ConsultarConta consultarConta = new ConsultarConta(mor);
           // consultarConta.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            System.out.println("Problemas ao cadastrar Pessoa na View!  Erro: " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnConsultarContaMouseClicked
   void setSaldo(){
       
       List<Object> moradores =  MoradorController.selectMoradors();
        
            Double saldoTotal = new Double(0);
            for (Object object : moradores) {
                Morador morador = (Morador) object;
                if(!morador.getLogin().equals(usuario.getLogin())){         
                    Double saldo = CompartilhadoController.remanejarUsuario(usuario.getLogin(), morador.getLogin()) - CompartilhadoController.remanejarUsuario( morador.getLogin(),usuario.getLogin());
                    saldoTotal += saldo;
                }
            }
            List<Object> contas = PessoalController.selectContaPessoal(usuario);
            for (Object object : contas) {
                Conta conta = (Conta) object;   
                saldoTotal -= conta.getValor();
             }
            jlblSaldo.setText(  String.format( "%.2f", saldoTotal) );
   }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Morador mor = new Morador();
        try {
            MoradorController moradorController = new MoradorController();

            mor = moradorController.login(usuario);
        } catch (Exception ex) {
            System.out.println("Problemas ao cadastrar Pessoa na View!  Erro: " + ex.getMessage());
            ex.printStackTrace();
        }
        try {

            CadastroMorador cadastroMorador = new CadastroMorador(mor);
            cadastroMorador.setVisible(true);
            CadastroMorador.btnCadastrarConta.setVisible(false);
            CadastroMorador.btnConsultarConta.setVisible(false);
            CadastroMorador.btnConsultarSaldo.setVisible(false);
            CadastroMorador.labelSaldo.setVisible(false);
            CadastroMorador.jtfSaldo.setVisible(false);
            CadastroMorador.jlblLogin.setVisible(true);
            CadastroMorador.jlblSenha.setVisible(true);
            CadastroMorador.jtfLogin.setVisible(true);
            CadastroMorador.jtfSenha.setVisible(true);
            CadastroMorador.btnCadastrar.setVisible(false);
            CadastroMorador.btnAlterar.setVisible(true);
            CadastroMorador.jtfNome.setText(usuario.getNome());
            CadastroMorador.jtfSobrenome.setText(usuario.getSobreNome());
            CadastroMorador.jtfEmail.setText(usuario.getEmail());
            CadastroMorador.jtfLogin.setText(usuario.getLogin());
            CadastroMorador.jtfSenha.setText(usuario.getSenha());

        } catch (Exception ex) {
            System.out.println("Erro: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCadastrarConta;
    private javax.swing.JLabel btnConsultarConta;
    private javax.swing.JLabel btnConsultarSaldo;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblSaudacao;
    private javax.swing.JLabel jlblSaldo;
    private org.edisoncor.gui.label.LabelRound labelRound1;
    private javax.swing.JLabel lblHora;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelNice panelNice5;
    private org.edisoncor.gui.panel.PanelNice panelNice6;
    // End of variables declaration//GEN-END:variables
}
